
spring.application.name=SportHub

# Configurazione della connessione al database
spring.datasource.url=jdbc:mysql://localhost:3306/SportHub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Nicola@96

# Configurazione del driver (spesso rilevato automaticamente, ma utile specificarlo)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione di Hibernate / JPA (gestione delle tabelle)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.baseline-on-migrate=true